// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace osp.dbc
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\nguye\Documents\GitHub\osp_ide\src\osp-dbc\osp-dbc\can_db.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class can_db : can_dbBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("module can_db\r\n\r\ndef id(cmd)\r\n    imp std:import/2\r\n\r\n    ldk \"id/0\"\r\n\r\n    imp s" +
                    "td-tuple:get/2\r\n    ldk 0\r\n    llv cmd\r\n    ivk 2\r\n\r\n    ivk 2\r\n    ret\r\nend\r\n\r\n" +
                    "def id_format(cmd)\r\n    imp std:import/2\r\n\r\n    ldk \"id_format/0\"\r\n\r\n    imp std" +
                    "-tuple:get/2\r\n    ldk 0\r\n    llv cmd\r\n    ivk 2\r\n\r\n    ivk 2\r\n    ret\r\nend\r\n\r\nde" +
                    "f dlc(cmd)\r\n    imp std:import/2\r\n\r\n    ldk \"dlc/0\"\r\n\r\n    imp std-tuple:get/2\r\n" +
                    "    ldk 0\r\n    llv cmd\r\n    ivk 2\r\n\r\n    ivk 2\r\n    ret\r\nend\r\n\r\ndef tx_method(cm" +
                    "d)\r\n    imp std:import/2\r\n\r\n    ldk \"tx_method/0\"\r\n\r\n    imp std-tuple:get/2\r\n  " +
                    "  ldk 0\r\n    llv cmd\r\n    ivk 2\r\n\r\n    ivk 2\r\n    ret\r\nend\r\n\r\ndef cycle_time(cmd" +
                    ")\r\n    imp std:import/2\r\n\r\n    ldk \"cycle_time/0\"\r\n\r\n    imp std-tuple:get/2\r\n  " +
                    "  ldk 0\r\n    llv cmd\r\n    ivk 2\r\n\r\n    ivk 2\r\n    ret\r\nend\r\n\r\ndef transmitter(cm" +
                    "d)\r\n    imp std:import/2\r\n\r\n    ldk \"transmitter/0\"\r\n\r\n    imp std-tuple:get/2\r\n" +
                    "    ldk 0\r\n    llv cmd\r\n    ivk 2\r\n\r\n    ivk 2\r\n    ret\r\nend\r\n\r\ndef set_signal(c" +
                    "md, signalname, value)\r\n    imp std:import/2\r\n    imp std-string:concat/2\r\n    l" +
                    "dk \"/2\"\r\n    imp std-string:concat/2\r\n    llv signalname\r\n    ldk \"set_\"\r\n    iv" +
                    "k 2\r\n    ivk 2\r\n    imp std-tuple:get/2\r\n    ldk 0\r\n    llv cmd\r\n    ivk 2\r\n    " +
                    "ivk 2\r\n    ret\r\nend\r\n\r\ndef serialize(cmd)\r\n    var [can_frm]\r\n    imp std:import" +
                    "/2\r\n    ldk \"serialize/1\"\r\n    imp std-tuple:get/2\r\n    ldk 0\r\n    llv cmd\r\n    " +
                    "ivk 2\r\n    ivk 2\r\n    llv cmd\r\n    ivk 1\r\n\r\n    slv can_frm\r\n    llv can_frm\r\n  " +
                    "  ret\r\nend\r\n\r\ndef deserialize(cmd)\r\n    imp std:import/2\r\n\r\n    ldk \"deserialize" +
                    "/1\"\r\n\r\n    imp std-tuple:get/2\r\n    ldk 0\r\n    llv cmd\r\n    ivk 2\r\n    ivk 2\r\n\r\n" +
                    "\r\n    llv cmd\r\n    ivk 1\r\n    ret\r\nend\r\n\r\ndef to_integer(value, minimum, resolut" +
                    "ion)\r\n    var [val_sub, val_div, val]\r\n\r\n    llv minimum\r\n    llv value\r\n    sub" +
                    "\r\n    slv val_sub\r\n\r\n    llv resolution\r\n    llv val_sub\r\n    div\r\n    slv val_d" +
                    "iv\r\n\r\n    imp std:to_integer/1\r\n    llv val_div\r\n    ivk 1\r\n    slv val\r\n\r\n    l" +
                    "lv val\r\n    ret\r\nend");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class can_dbBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
