shallow_clone: false

branches:
  only: 
    - master

notifications:
  - provider: Webhook
    url: 
      secure: bIlX/+KpPM+ScK25WusZGPz885QS8RPaTKj/9qc9Pf68y7c+lJPbcyxeRlHpBzN8bN8RRx0PPuGendeGDOWuoXIZ1haDMGYEotIwFdmgU4ExIZwZFh69KLcJUuJn5AoySbelvUiKG+vWhKsq1QCKpB6dw//0scWQHA53SRWYVmcbmWd5i1Rb5M5qClALcpP8
    method: POST
    on_build_success: true
    on_build_failure: true

matrix:
  fast_finish: true

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    TOOLSET: 'Visual Studio 15 2017'       
    AMLC: 'On'
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    TOOLSET: 'Visual Studio 15 2017 Win64'       
    AMLC: 'On'

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    TOOLSET: 'Visual Studio 14 2015'       
    AMLC: 'On'
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    TOOLSET: 'Visual Studio 14 2015 Win64'       
    AMLC: 'On'

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    TOOLSET: 'Visual Studio 12 2013'       
    AMLC: 'Off'
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    TOOLSET: 'Visual Studio 12 2013 Win64'       
    AMLC: 'Off'

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    TOOLSET: 'Visual Studio 11 2012'       
    AMLC: 'Off'
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    TOOLSET: 'Visual Studio 11 2012 Win64'       
    AMLC: 'Off'

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    TOOLSET: 'Visual Studio 10 2010'       
    AMLC: 'Off'
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    TOOLSET: 'Visual Studio 10 2010 Win64'       
    AMLC: 'Off'

configuration:
  - Debug
  - Release
  - MinSizeRel
  - RelWithDebInfo

install:
  - git submodule update --init --recursive
  - cmake -G "%TOOLSET%" -DTASK_BACKEND=fiber -DAMLC="%AMLC%"

build_script:
  - cmake --build . --config %CONFIGURATION%
  - ctest -C %CONFIGURATION% -V --timeout 300
